#!/usr/bin/env bash
uv run candles/miner/miner.py --axon.external_ip 18.189.185.159 --netuid 357 --axon.port 8092 --subtensor.network test --wallet.name miner --wallet.hotkey miner_default --blacklist.validator_min_stake 0 --logging.info
