name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run linting with ruff
      run: |
        uv run ruff check .

    - name: Run tests with pytest
      run: |
        uv run pytest tests/ --asyncio-mode=auto -v

    - name: Upload coverage reports
      if: matrix.python-version == '3.12'
      run: |
        uv add --dev coverage[toml]
        uv run coverage run -m pytest tests/ --asyncio-mode=auto
        uv run coverage xml
      continue-on-error: true

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.12'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      continue-on-error: true
